version: '3'

services:
  app:
    build: .
    container_name: telegram_message_monitor
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./config.json:/usr/src/app/src/config.json
    restart: always
