version: '3'
services:
  main_bot:
    build: .
    container_name: main_bot
    volumes:
      - ./config.json:/app/config.json
    command: python src/bot.py

  management_bot:
    build: .
    container_name: management_bot
    volumes:
      - ./config.json:/app/config.json
    command: python src/management_bot.py